<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		
		<LangVersion>12</LangVersion>
		<IsPackable>false</IsPackable>
		<UserSecretsId>704a0043-27b2-431d-9835-bad916c45ecd</UserSecretsId>
	</PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="coverlet.collector" Version="6.0.0" />
	  <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="9.0.10" />
	  <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.10" />
	  <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
	  <PackageReference Include="NUnit" Version="3.14.0" />
	  <PackageReference Include="NUnit.Analyzers" Version="3.9.0" />
	  <PackageReference Include="NUnit3TestAdapter" Version="4.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RepetierServerSharpApi\RepetierServerSharpApi.csproj" />
  </ItemGroup>

	<ItemGroup>
		<Using Include="NUnit.Framework" />
	</ItemGroup>
</Project>
